In [557]:
import numpy as np
import pandas as pd

# pandas

In [558]:
dict1 = {
    'name': ['goutam', 'rohan', 'shiv'],
    'marks': [92, 34, 24],
    'city': ['khargone', 'mumbai', 'delhi']
}

In [559]:
df = pd.DataFrame(dict1)

In [560]:
df

     name  marks      city
0  goutam     92  khargone
1   rohan     34    mumbai
2    shiv     24     delhi

In [561]:
df.to_csv('goutam.csv')

In [562]:
df.to_csv('frinds.csv',index=False)

In [563]:
df.head(2)

     name  marks      city
0  goutam     92  khargone
1   rohan     34    mumbai

In [564]:
df.tail(2)

    name  marks    city
1  rohan     34  mumbai
2   shiv     24   delhi

In [565]:
df.describe()

          marks
count   3.00000
mean   50.00000
std    36.71512
min    24.00000
25%    29.00000
50%    34.00000
75%    63.00000
max    92.00000

In [566]:
goutam = pd.read_csv('goutam.csv')

In [567]:
goutam

   Unnamed: 0    name  marks      city
0           0  goutam     92  khargone
1           1   rohan     34    mumbai
2           2    shiv     24     delhi

In [568]:
goutam.index=['first','second','third']

In [569]:
goutam

        Unnamed: 0    name  marks      city
first            0  goutam     92  khargone
second           1   rohan     34    mumbai
third            2    shiv     24     delhi

In [570]:
ser = pd.Series(np.random.rand(34))

In [571]:
ser

0     0.476719
1     0.150697
2     0.895431
3     0.719821
4     0.256876
5     0.700999
6     0.966640
7     0.333571
8     0.219881
9     0.368980
10    0.746034
11    0.025009
12    0.771070
13    0.839669
14    0.270484
15    0.657727
16    0.300978
17    0.809376
18    0.283567
19    0.174672
20    0.438175
21    0.121200
22    0.709756
23    0.235004
24    0.553765
25    0.281760
26    0.510049
27    0.115629
28    0.768460
29    0.495492
30    0.793677
31    0.685102
32    0.738304
33    0.444792
dtype: float64

In [572]:
type(ser)

pandas.core.series.Series

In [573]:
newdf = pd.DataFrame(np.random.rand(334, 5), index=np.arange(334))

In [574]:
type(newdf)
newdf.head()

          0         1         2         3         4
0  0.074383  0.215545  0.330874  0.364221  0.536701
1  0.058932  0.165172  0.971120  0.978663  0.853689
2  0.121700  0.860331  0.129802  0.412914  0.421412
3  0.250880  0.149263  0.870510  0.391007  0.914377
4  0.800924  0.317642  0.240948  0.508859  0.292414

In [575]:
newdf

            0         1         2         3         4
0    0.074383  0.215545  0.330874  0.364221  0.536701
1    0.058932  0.165172  0.971120  0.978663  0.853689
2    0.121700  0.860331  0.129802  0.412914  0.421412
3    0.250880  0.149263  0.870510  0.391007  0.914377
4    0.800924  0.317642  0.240948  0.508859  0.292414
..        ...       ...       ...       ...       ...
329  0.039602  0.550700  0.818775  0.476773  0.663764
330  0.898992  0.641474  0.919845  0.901328  0.348826
331  0.453719  0.083554  0.076352  0.860460  0.127484
332  0.820095  0.532050  0.585757  0.775042  0.004107
333  0.891920  0.973679  0.757441  0.609720  0.844572

[334 rows x 5 columns]

In [576]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [577]:
newdf[0][0] = "g"

C:\Users\Asus\AppData\Local\Temp\ipykernel_13460\4231433982.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = "g"
C:\Users\Asus\AppData\Local\Temp\ipykernel_13460\4231433982.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'g' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = "g"

In [578]:
newdf

            0         1         2         3         4
0           g  0.215545  0.330874  0.364221  0.536701
1    0.058932  0.165172  0.971120  0.978663  0.853689
2      0.1217  0.860331  0.129802  0.412914  0.421412
3     0.25088  0.149263  0.870510  0.391007  0.914377
4    0.800924  0.317642  0.240948  0.508859  0.292414
..        ...       ...       ...       ...       ...
329  0.039602  0.550700  0.818775  0.476773  0.663764
330  0.898992  0.641474  0.919845  0.901328  0.348826
331  0.453719  0.083554  0.076352  0.860460  0.127484
332  0.820095  0.532050  0.585757  0.775042  0.004107
333   0.89192  0.973679  0.757441  0.609720  0.844572

[334 rows x 5 columns]

In [579]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [580]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [581]:
newdf.to_numpy()

array([['g', 0.21554461424646554, 0.3308738867903933,
        0.36422085972548923, 0.5367014070653251],
       [0.058932499441559205, 0.16517198840782676, 0.9711203269814548,
        0.9786627223870231, 0.853689413404496],
       [0.12169979674456932, 0.8603310550625832, 0.1298016149450657,
        0.41291362528873476, 0.42141162210443495],
       ...,
       [0.45371924770088523, 0.08355394862583321, 0.0763518826398184,
        0.8604604164703847, 0.12748388172480218],
       [0.8200946598998129, 0.5320503110701998, 0.5857571531860662,
        0.7750415611342546, 0.00410692705344029],
       [0.891919834333271, 0.9736790830653456, 0.7574414334591862,
        0.6097195177883399, 0.844571951659956]], dtype=object)

In [582]:
newdf[0][0]=0.3

In [583]:
newdf.head()

          0         1         2         3         4
0       0.3  0.215545  0.330874  0.364221  0.536701
1  0.058932  0.165172  0.971120  0.978663  0.853689
2    0.1217  0.860331  0.129802  0.412914  0.421412
3   0.25088  0.149263  0.870510  0.391007  0.914377
4  0.800924  0.317642  0.240948  0.508859  0.292414

In [584]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.3,0.058932,0.1217,0.25088,0.800924,0.379748,0.619917,0.733557,0.303834,0.347507,...,0.150322,0.02277,0.684279,0.09963,0.934666,0.039602,0.898992,0.453719,0.820095,0.89192
1,0.215545,0.165172,0.860331,0.149263,0.317642,0.461421,0.181892,0.993634,0.907188,0.73676,...,0.515071,0.377699,0.405386,0.3574,0.002735,0.5507,0.641474,0.083554,0.53205,0.973679
2,0.330874,0.97112,0.129802,0.87051,0.240948,0.83243,0.295344,0.946463,0.875128,0.739059,...,0.375113,0.350365,0.375206,0.642358,0.063293,0.818775,0.919845,0.076352,0.585757,0.757441
3,0.364221,0.978663,0.412914,0.391007,0.508859,0.671334,0.526456,0.271711,0.995969,0.078261,...,0.55742,0.275112,0.876219,0.571067,0.554394,0.476773,0.901328,0.86046,0.775042,0.60972
4,0.536701,0.853689,0.421412,0.914377,0.292414,0.958993,0.340103,0.080946,0.741686,0.461836,...,0.041859,0.928833,0.78648,0.497683,0.559727,0.663764,0.348826,0.127484,0.004107,0.844572

In [585]:
newdf

            0         1         2         3         4
0         0.3  0.215545  0.330874  0.364221  0.536701
1    0.058932  0.165172  0.971120  0.978663  0.853689
2      0.1217  0.860331  0.129802  0.412914  0.421412
3     0.25088  0.149263  0.870510  0.391007  0.914377
4    0.800924  0.317642  0.240948  0.508859  0.292414
..        ...       ...       ...       ...       ...
329  0.039602  0.550700  0.818775  0.476773  0.663764
330  0.898992  0.641474  0.919845  0.901328  0.348826
331  0.453719  0.083554  0.076352  0.860460  0.127484
332  0.820095  0.532050  0.585757  0.775042  0.004107
333   0.89192  0.973679  0.757441  0.609720  0.844572

[334 rows x 5 columns]

In [586]:
newdf.sort_index(axis=0 , ascending=False)

            0         1         2         3         4
333   0.89192  0.973679  0.757441  0.609720  0.844572
332  0.820095  0.532050  0.585757  0.775042  0.004107
331  0.453719  0.083554  0.076352  0.860460  0.127484
330  0.898992  0.641474  0.919845  0.901328  0.348826
329  0.039602  0.550700  0.818775  0.476773  0.663764
..        ...       ...       ...       ...       ...
4    0.800924  0.317642  0.240948  0.508859  0.292414
3     0.25088  0.149263  0.870510  0.391007  0.914377
2      0.1217  0.860331  0.129802  0.412914  0.421412
1    0.058932  0.165172  0.971120  0.978663  0.853689
0         0.3  0.215545  0.330874  0.364221  0.536701

[334 rows x 5 columns]

In [587]:
newdf.sort_index(axis=1 , ascending=False)

            4         3         2         1         0
0    0.536701  0.364221  0.330874  0.215545       0.3
1    0.853689  0.978663  0.971120  0.165172  0.058932
2    0.421412  0.412914  0.129802  0.860331    0.1217
3    0.914377  0.391007  0.870510  0.149263   0.25088
4    0.292414  0.508859  0.240948  0.317642  0.800924
..        ...       ...       ...       ...       ...
329  0.663764  0.476773  0.818775  0.550700  0.039602
330  0.348826  0.901328  0.919845  0.641474  0.898992
331  0.127484  0.860460  0.076352  0.083554  0.453719
332  0.004107  0.775042  0.585757  0.532050  0.820095
333  0.844572  0.609720  0.757441  0.973679   0.89192

[334 rows x 5 columns]

In [555]:
newdf.head()

          1         2     3         4
0  0.673790  0.931333  34.0  0.343211
1  0.157741  0.123906  34.0  0.814882
2  0.418204  0.166496  34.0  0.462686
3  0.483952  0.270035  34.0  0.241626
4  0.782073  0.357852  34.0  0.901091

In [588]:
type(newdf[1])

pandas.core.series.Series

In [589]:
newdf2= newdf

In [590]:
newdf2[0][0]=9789

In [591]:
newdf

            0         1         2         3         4
0        9789  0.215545  0.330874  0.364221  0.536701
1    0.058932  0.165172  0.971120  0.978663  0.853689
2      0.1217  0.860331  0.129802  0.412914  0.421412
3     0.25088  0.149263  0.870510  0.391007  0.914377
4    0.800924  0.317642  0.240948  0.508859  0.292414
..        ...       ...       ...       ...       ...
329  0.039602  0.550700  0.818775  0.476773  0.663764
330  0.898992  0.641474  0.919845  0.901328  0.348826
331  0.453719  0.083554  0.076352  0.860460  0.127484
332  0.820095  0.532050  0.585757  0.775042  0.004107
333   0.89192  0.973679  0.757441  0.609720  0.844572

[334 rows x 5 columns]

In [592]:
newdf2

            0         1         2         3         4
0        9789  0.215545  0.330874  0.364221  0.536701
1    0.058932  0.165172  0.971120  0.978663  0.853689
2      0.1217  0.860331  0.129802  0.412914  0.421412
3     0.25088  0.149263  0.870510  0.391007  0.914377
4    0.800924  0.317642  0.240948  0.508859  0.292414
..        ...       ...       ...       ...       ...
329  0.039602  0.550700  0.818775  0.476773  0.663764
330  0.898992  0.641474  0.919845  0.901328  0.348826
331  0.453719  0.083554  0.076352  0.860460  0.127484
332  0.820095  0.532050  0.585757  0.775042  0.004107
333   0.89192  0.973679  0.757441  0.609720  0.844572

[334 rows x 5 columns]

In [593]:
newdf.loc[0,0]=654

In [594]:
newdf.head(2)

          0         1         2         3         4
0       654  0.215545  0.330874  0.364221  0.536701
1  0.058932  0.165172  0.971120  0.978663  0.853689

In [595]:
newdf.coluns = list("AE")

C:\Users\Asus\AppData\Local\Temp\ipykernel_13460\343458721.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  newdf.coluns = list("AE")

In [596]:
newdf.head(2)

          0         1         2         3         4
0       654  0.215545  0.330874  0.364221  0.536701
1  0.058932  0.165172  0.971120  0.978663  0.853689

In [597]:
newdf=newdf.drop(0,axis=1)

In [598]:
newdf

            1         2         3         4
0    0.215545  0.330874  0.364221  0.536701
1    0.165172  0.971120  0.978663  0.853689
2    0.860331  0.129802  0.412914  0.421412
3    0.149263  0.870510  0.391007  0.914377
4    0.317642  0.240948  0.508859  0.292414
..        ...       ...       ...       ...
329  0.550700  0.818775  0.476773  0.663764
330  0.641474  0.919845  0.901328  0.348826
331  0.083554  0.076352  0.860460  0.127484
332  0.532050  0.585757  0.775042  0.004107
333  0.973679  0.757441  0.609720  0.844572

[334 rows x 4 columns]

newdf.head()

In [599]:
newdf.loc[[1, 2], [2, 3]]

          2         3
1  0.971120  0.978663
2  0.129802  0.412914

In [600]:
newdf[newdf[3] < 0.3]

            1         2         3         4
7    0.993634  0.946463  0.271711  0.080946
9    0.736760  0.739059  0.078261  0.461836
12   0.587026  0.460742  0.178880  0.411738
15   0.610957  0.286826  0.128021  0.215294
18   0.884693  0.901606  0.148410  0.385654
..        ...       ...       ...       ...
310  0.846111  0.950049  0.161696  0.838122
312  0.688866  0.246785  0.176897  0.436760
316  0.420800  0.146494  0.072940  0.668297
321  0.946064  0.416066  0.142724  0.384445
325  0.377699  0.350365  0.275112  0.928833

[98 rows x 4 columns]

In [601]:
newdf.iloc[0, 2]

np.float64(0.36422085972548923)

In [602]:
newdf.iloc[[0,5],[1,2]]

          2         3
0  0.330874  0.364221
5  0.832430  0.671334

In [603]:
newdf.head(3)

          1         2         3         4
0  0.215545  0.330874  0.364221  0.536701
1  0.165172  0.971120  0.978663  0.853689
2  0.860331  0.129802  0.412914  0.421412

In [604]:
newdf.drop(0)

            1         2         3         4
1    0.165172  0.971120  0.978663  0.853689
2    0.860331  0.129802  0.412914  0.421412
3    0.149263  0.870510  0.391007  0.914377
4    0.317642  0.240948  0.508859  0.292414
5    0.461421  0.832430  0.671334  0.958993
..        ...       ...       ...       ...
329  0.550700  0.818775  0.476773  0.663764
330  0.641474  0.919845  0.901328  0.348826
331  0.083554  0.076352  0.860460  0.127484
332  0.532050  0.585757  0.775042  0.004107
333  0.973679  0.757441  0.609720  0.844572

[333 rows x 4 columns]

In [605]:
newdf.drop([1,2])

            1         2         3         4
0    0.215545  0.330874  0.364221  0.536701
3    0.149263  0.870510  0.391007  0.914377
4    0.317642  0.240948  0.508859  0.292414
5    0.461421  0.832430  0.671334  0.958993
6    0.181892  0.295344  0.526456  0.340103
..        ...       ...       ...       ...
329  0.550700  0.818775  0.476773  0.663764
330  0.641474  0.919845  0.901328  0.348826
331  0.083554  0.076352  0.860460  0.127484
332  0.532050  0.585757  0.775042  0.004107
333  0.973679  0.757441  0.609720  0.844572

[332 rows x 4 columns]

In [606]:
newdf.drop([1,2],axis=1)

            3         4
0    0.364221  0.536701
1    0.978663  0.853689
2    0.412914  0.421412
3    0.391007  0.914377
4    0.508859  0.292414
..        ...       ...
329  0.476773  0.663764
330  0.901328  0.348826
331  0.860460  0.127484
332  0.775042  0.004107
333  0.609720  0.844572

[334 rows x 2 columns]

In [607]:
newdf

            1         2         3         4
0    0.215545  0.330874  0.364221  0.536701
1    0.165172  0.971120  0.978663  0.853689
2    0.860331  0.129802  0.412914  0.421412
3    0.149263  0.870510  0.391007  0.914377
4    0.317642  0.240948  0.508859  0.292414
..        ...       ...       ...       ...
329  0.550700  0.818775  0.476773  0.663764
330  0.641474  0.919845  0.901328  0.348826
331  0.083554  0.076352  0.860460  0.127484
332  0.532050  0.585757  0.775042  0.004107
333  0.973679  0.757441  0.609720  0.844572

[334 rows x 4 columns]

# implace = true means make changes in orignal  data

In [608]:
newdf.reset_index()

     index         1         2         3         4
0        0  0.215545  0.330874  0.364221  0.536701
1        1  0.165172  0.971120  0.978663  0.853689
2        2  0.860331  0.129802  0.412914  0.421412
3        3  0.149263  0.870510  0.391007  0.914377
4        4  0.317642  0.240948  0.508859  0.292414
..     ...       ...       ...       ...       ...
329    329  0.550700  0.818775  0.476773  0.663764
330    330  0.641474  0.919845  0.901328  0.348826
331    331  0.083554  0.076352  0.860460  0.127484
332    332  0.532050  0.585757  0.775042  0.004107
333    333  0.973679  0.757441  0.609720  0.844572

[334 rows x 5 columns]

In [609]:
newdf.loc[:,[3]]=34

In [610]:
newdf

            1         2     3         4
0    0.215545  0.330874  34.0  0.536701
1    0.165172  0.971120  34.0  0.853689
2    0.860331  0.129802  34.0  0.421412
3    0.149263  0.870510  34.0  0.914377
4    0.317642  0.240948  34.0  0.292414
..        ...       ...   ...       ...
329  0.550700  0.818775  34.0  0.663764
330  0.641474  0.919845  34.0  0.348826
331  0.083554  0.076352  34.0  0.127484
332  0.532050  0.585757  34.0  0.004107
333  0.973679  0.757441  34.0  0.844572

[334 rows x 4 columns]

In [611]:
df = pd.DataFrame({
    "name": ['Alfred', 'Batman', 'Alfred'],
    "toy": [np.nan, 'Batmobile', 'Bullwhip'],
    "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT]
})

In [612]:
df

     name        toy       born
0  Alfred        NaN        NaT
1  Batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [613]:
df.head()

     name        toy       born
0  Alfred        NaN        NaT
1  Batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [614]:
df.dropna(how='all')

     name        toy       born
0  Alfred        NaN        NaT
1  Batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [615]:
df

     name        toy       born
0  Alfred        NaN        NaT
1  Batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [616]:
df.dropna(how='all',axis=1)

     name        toy       born
0  Alfred        NaN        NaT
1  Batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [617]:
df.drop_duplicates(subset=['name'])

     name        toy       born
0  Alfred        NaN        NaT
1  Batman  Batmobile 1940-04-25

In [618]:
df.shape

(3, 3)

In [619]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   toy     2 non-null      object
 2   born    1 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(2)
memory usage: 204.0+ bytes

In [620]:
df['name'].value_counts(dropna=False)

name
Alfred    2
Batman    1
Name: count, dtype: int64

In [621]:
df['name'].value_counts(dropna=True)

name
Alfred    2
Batman    1
Name: count, dtype: int64

In [622]:
df.isnull()

    name    toy   born
0  False   True   True
1  False  False  False
2  False  False   True

In [623]:
df.notnull()

   name    toy   born
0  True  False  False
1  True   True   True
2  True   True  False

In [624]:
df = pd.DataFrame({
    'A': [10, 20, 30],
    'B': [5, 15, 25]
})

In [625]:
df

    A   B
0  10   5
1  20  15
2  30  25

In [626]:
df.describe()

          A     B
count   3.0   3.0
mean   20.0  15.0
std    10.0  10.0
min    10.0   5.0
25%    15.0  10.0
50%    20.0  15.0
75%    25.0  20.0
max    30.0  25.0

In [627]:
df.mean()

A    20.0
B    15.0
dtype: float64

In [628]:
df.corr()

     A    B
A  1.0  1.0
B  1.0  1.0

In [629]:
df.count()

A    3
B    3
dtype: int64

In [630]:
df.max()

A    30
B    25
dtype: int64

In [631]:
df.min()

A    10
B     5
dtype: int64

In [632]:
df.median()

A    20.0
B    15.0
dtype: float64

In [633]:
df.std()

A    10.0
B    10.0
dtype: float64

In [634]:
data = pd.read_excel('sheet1.xlsx')

In [635]:
data

   roll No      name      city  marks subjext
0      101  Goutama\  Khargone     99    math
1      102    Shivam  Khargone     98    math
2      103    Diksha  Khargone     97    math
3      104    Devang  Khargone     96    math

In [636]:
data = pd.read_excel('sheet1.xlsx',Sheet_name = 'sheet2.xlsx')

TypeError: read_excel() got an unexpected keyword argument 'Sheet_name'